"""empty message

Revision ID: 031d539ab1b7
Revises: 9caae8ee59d7
Create Date: 2021-03-01 18:19:02.044639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031d539ab1b7'
down_revision = '9caae8ee59d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favplanets', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favplanets', 'name')
    # ### end Alembic commands ###
