"""empty message

Revision ID: 1af260f34b39
Revises: 031d539ab1b7
Create Date: 2021-03-01 18:25:44.394922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af260f34b39'
down_revision = '031d539ab1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favcharacters', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favcharacters', 'name')
    # ### end Alembic commands ###
