"""empty message

Revision ID: cccb213e61a1
Revises: cbc7a342686f
Create Date: 2021-02-27 20:48:57.419348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccb213e61a1'
down_revision = 'cbc7a342686f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favcharacters', sa.Column('typeOfFav', sa.String(length=50), nullable=False))
    op.add_column('favplanets', sa.Column('typeOfFav', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favplanets', 'typeOfFav')
    op.drop_column('favcharacters', 'typeOfFav')
    # ### end Alembic commands ###
